Problem Statement 1:

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.


Returns:	
out : ndarray

Vandermonde matrix. If increasing is False, the first column is x^(N-1), the second x^(N-2) and so forth. If increasing is True, the columns are x^0, x^1, ..., x^(N-1)


In [18]:
import numpy as np
# numpy.vander(x, N=None, increasing=False)[source]

def my_vander(): # where x is an array of integers():
    #x = np.array([1,2,3,4,5])
    x = np.array([4,5,6,7])
    N = int(len(x))
    #print(N)
    #print(x)
    y = np.vander(x, N, increasing=False)
    #y = np.vander(x, N, increasing=True)
    print(y)

my_vander()


4
[4 5 6 7]
[[ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]
 [343  49   7   1]]


#### 